### ISSUE TITLE
add "skip" and "rewind" intents

### ISSUE THREAD

**Issue by JarbasAl** [MycroftAI/skill-playback-control#14]
https://github.com/MycroftAI/mycroft-core/pull/1944 adds audioservice support for seeking in currently playing track, once merged intents should be done for it

"hey mycroft, rewind 5 seconds"
"hey mycroft, skip 10 seconds"
"hey mycroft, seek 20 seconds"
"hey mycroft, seek minus 50 seconds"

**Comment by pixelherodev** [comment]
As a heads up, any implementation of this will need to ensure that the currently playing skill supports seeking in the current song. Pianobar for instance, which the Pandora skill uses for all the heavy lifting, does not support changing position within the current song.
