### ISSUE TITLE
translation isue - translated play dosnt get removed from data

### ISSUE THREAD

**Issue by andlo** [MycroftAI/skill-playback-control#20]
It seems like that if I translate the Play.voc the words dosnt get removed from the data. If I keep play in the voc file and use play it is removed.

Tryed to figure out why and where but didnt really find the problem. 

I did see hardcoded lang='en-us' ut dossnt seem to be the issue. 

Also did see this
```
           if not voc:
                voc = resolve_resource_file(join('text', lang,
                                                 voc_filename + '.voc'))
```
but the resolve_resource_file seems to be undefined. But again I am not sure it is related to my problem.

**Comment by forslund** [comment]
Hmmm, works for me. What does your Play.voc look like and what does your Phrase.rx look like? And what phrase are you trying with?

**Comment by andlo** [comment]
phrase.rx:
play (?P<Phrase>.*)
spil (?P<Phrase>.*)
start (?P<Phrase>.*)
bork (?P<Phrase>.*)

Play.voc:
spil
start
bork
play

The strange thing is it works useing play XXXX but not spil XXXX

**Comment by forslund** [comment]
Did github eat part off your phrase.rx?

This is what the Swedish looks like right now:
phrase.rx
```
spela upp (?P<Phrase>.*)
starta (?P<Phrase>.*)
bork (?P<Phrase>.*)
```
Play.voc:
```
spela upp
starta
bork
```

I'll check with your values, and I'll assume the regex was eaten by github

**Comment by andlo** [comment]
Yah he tok some thing away....
```
play (?P<Phrase>.*)
spil (?P<Phrase>.*)
start (?P<Phrase>.*)
bork (?P<Phrase>.*)
```

**Comment by forslund** [comment]
Weird, exactly those works for me when I insert them into the swedish translation :/

**Comment by andlo** [comment]
Then I try copying swedish and see what happens :)

**Comment by andlo** [comment]
No dosnt work....

I try with the tune in skill and "spil dr p1 med tune in" wich dosnt work, but "play dr p1 med tune in does" 
And can se in log that the fist dosnt rip the spil but second does rip play.....

strange

**Comment by forslund** [comment]
Just to verify: your lang is set to danish and not still on english?

**Comment by andlo** [comment]
it seems that it is related to spil as if I add ostemad to Play.voc and Phrase.rx and use "ostemad dr p1 med tune in" it does work.....
And yes language is set to da-dk and when copying the sv-se I got funny talk from mycroft when testing :)

**Comment by forslund** [comment]
Verified the phrase and it works here... Very strange....

**Comment by andlo** [comment]
Ohhh the funnytalk is in english....but he resads the da play.voc and phrase.rx as ostemad did work.....
and the skill replyes in danish as everything else does....

**Comment by forslund** [comment]
Do you have other skills that reacts to "spil" that may override the playback control skill?

**Comment by andlo** [comment]
could it be related to resolve_resource_file on line 58 pyflaxe says it is undefined ?

![image](https://user-images.githubusercontent.com/3314671/53973285-c6a4b800-4100-11e9-8955-bc398d3460b7.png)

I can se in the log that it is the common play skill that handles and it is the tune in that replyes.....

**Comment by forslund** [comment]
That is an issue but it isn't used here (it's old backwards compatibility code I think)

The splitting should be handled here: https://github.com/MycroftAI/skill-playback-control/blob/19.02/__init__.py#L137

**Comment by andlo** [comment]
Ill put in som log lines and see what happens around line 137

**Comment by andlo** [comment]
I see this
```
[0:07] Decoding of A03H.mp3 finished.
18:08:28.245 - Playback Control Skill - INFO - utterance
18:08:28.246 - Playback Control Skill - INFO - Spil
18:08:28.247 - Playback Control Skill - INFO - Resolving Player for: spil p1 med tune in
18:08:33.037 - Playback Control Skill - INFO - Playing with: mycroft-skill-tunein
18:08:40.129 - Playback Control Skill - INFO - utterance
18:08:40.130 - Playback Control Skill - INFO - play
18:08:40.130 - Playback Control Skill - INFO - Resolving Player for: dr p1 på tune in
18:08:45.090 - Playback Control Skill - INFO - Playing with: mycroft-skill-tunein
```
What i notise is that Spil is capitalised even though I entered spil in the cli.....

I put in to loglines - one for utterance and one for self.log.info(message.data['Play']) to se what it hold...

**Comment by forslund** [comment]
Oh that is strange. But it would explain the issue. Can you try adding the capitalized Spil to the voc?

**Comment by andlo** [comment]
did try that and did try adding message.data['Play'].lower()  in line 139 to make sure it used lower letters. 
Nothing helps.....Other words does but not spil ;) 

afspil works.....but not spil realy strange.

**Comment by penrods** [comment]
Slight tangent, but in the same area:

I realized a few days ago that I left "bork" in there accidentally from early testing -- I needed something that was distinct from Play before CommonPlay had been implemented.  Whoops!

I was also talking to the skills team about removing "start" and just using "play" as the trigger on this.  Any strong feelings from you two?

**Comment by andlo** [comment]
I never have strong feelings ;) 
It is still strange that all words works except "spil" :)

**Comment by forslund** [comment]
start isn't a phrase I ever use so I'm fine with removing it.

**Comment by andlo** [comment]
You never guess - today spil works.....Cant see any changes but it works. And it isnt because of changes to my voice, as I always test using the cli.
But it do work - really strange.
